import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333';
const ID='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',ORPHAN='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
test('admin codes, user summaries and slide files enforce server-side permissions',async()=>{
 const db=new PGlite();
 try{
  await db.exec(`create role anon;create role authenticated;create schema auth;
   create table auth.users(id uuid primary key,email text,created_at timestamptz default now(),last_sign_in_at timestamptz);
   insert into auth.users(id,email) values('${A}','admin@example.test'),('${B}','student@example.test'),('${C}','other@example.test');
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;
   create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
   create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb,unique(bucket_id,name));
   alter table storage.objects enable row level security;grant usage on schema storage to authenticated;
   grant select,insert,delete on storage.objects to authenticated;
   create function storage.foldername(name text) returns text[] language sql immutable as $$select string_to_array(name,'/')$$;
   grant execute on function storage.foldername(text) to authenticated;`);
  await db.exec(readFileSync(new URL('../supabase/setup.sql',import.meta.url),'utf8'));
  const sql=readFileSync(new URL('../supabase/admin.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
  await db.exec(readFileSync(new URL('../supabase/delivery.sql',import.meta.url),'utf8'));
  for(const file of ['admin-view.sql','prepared-decks.sql'])await db.exec(readFileSync(new URL('../supabase/'+file,import.meta.url),'utf8'));
  const code=(await db.query(readFileSync(new URL('../supabase/admin-code.sql',import.meta.url),'utf8'))).rows[0].admin_unlock_code;
  assert.ok(code.length>60);
  const login=async id=>db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${id}';`);
  const isAdmin=async()=>(await db.query('select public.is_study_admin() result')).rows[0].result;
  const dash=async(...args)=>(await db.query('select public.study_admin_dashboard($1,$2,$3) result',args.length?args:[0,0,''])).rows[0].result;
  const upload=async(owner,id=ID)=>db.query("insert into storage.objects(bucket_id,name,metadata) values('lecture-submissions',$1,'{\"size\":123}')",[`${owner}/${id}/source.pdf`]);
  const submit=async(id=ID,size=123)=>db.query("select public.submit_study_lecture($1,'Lecture','pathobiology','Please make cards','lecture.pdf',$2,'pdf')",[id,size]);
  await login(B);assert.equal(await isAdmin(),false);
  await assert.rejects(db.query('select * from public.study_admin_codes'),/permission denied/);
  await assert.rejects(db.query('insert into public.study_admins(user_id) values($1)',[B]),/permission denied/);
  await assert.rejects(db.query('select public.unlock_study_admin($1)',['incorrect-but-long-enough-code']),/Invalid or expired/);
  await assert.rejects(dash(),/Admin access required/);
  await assert.rejects(upload(A),/row-level security/);
  await assert.rejects(submit(),/Upload the complete/);
  await upload(B);await assert.rejects(submit(ID,122),/Upload the complete/);await submit();
  assert.equal((await db.query('select * from public.lecture_submissions')).rows.length,1);
  await assert.rejects(db.query('update public.lecture_submissions set status=\'completed\''),/permission denied/);
  await login(C);assert.equal((await db.query('select * from public.lecture_submissions')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
  await assert.rejects(db.query("select public.review_study_submission($1,'completed','Hello')",[ID]),/Admin access required/);
  await login(A);await db.query('select public.unlock_study_admin($1)',[code]);assert.equal(await isAdmin(),true);
  await db.query('select public.save_study_deck($1,$2::jsonb,0)',['test',JSON.stringify({lectureId:'test',cards:[{id:'secret',question:'Private question',reviews:1},{id:'bad',reviews:'bad'},{id:'overflow',reviews:'9999999999999999999999999999'}]})]);
  await db.query("insert into public.study_decks(user_id,lecture_id,payload) values($1,'malformed','{\"cards\":{\"not\":\"an array\"}}')",[A]);
  const data=await dash();assert.equal(data.user_count,3);assert.equal(data.submissions[0].sender_email,'student@example.test');assert.equal(data.users.find(u=>u.id===A).studied_cards,1);
  assert.equal(JSON.stringify(data).includes('Private question'),false);assert.equal('payload' in data.users[0],false);
  assert.equal((await db.query('select * from storage.objects')).rows.length,1);
  await assert.rejects(db.query("select public.review_study_submission($1,'invalid','Hello')",[ID]),/Invalid review/);
  await db.query("select public.review_study_submission($1,'completed','Deck ready soon')",[ID]);
  await login(B);await assert.rejects(db.query('select public.unlock_study_admin($1)',[code]),/Invalid or expired/);
  const reply=(await db.query('select * from public.lecture_submissions')).rows[0];assert.equal(reply.status,'completed');assert.equal(reply.admin_reply,'Deck ready soon');
  assert.equal((await db.query('delete from storage.objects')).affectedRows,0,'submitted files cannot be removed by sender');
  await upload(B,ORPHAN);assert.equal((await db.query('delete from storage.objects')).affectedRows,1,'failed unsubmitted uploads can be cleaned up');
  await assert.rejects(db.query("select public.submit_study_lecture($1,'Lecture','','','bad.html',123,'pdf')",[ORPHAN]),/Invalid slide submission/);
  await db.exec('reset role;');
  for(let i=0;i<26;i++)await db.query('insert into auth.users(id,email) values(gen_random_uuid(),$1)',[`page${i}@example.test`]);
  await db.query("insert into public.study_admin_codes(code_hash,expires_at) values(sha256(convert_to($1,'UTF8')),now()-interval '1 second')",['expired-code-long-enough']);
  await login(C);await assert.rejects(db.query('select public.unlock_study_admin($1)',['expired-code-long-enough']),/Invalid or expired/);
  await login(A);assert.equal((await dash(0,0,'page')).users.length,25);assert.equal((await dash(1,0,'page')).users.length,1);assert.equal((await dash(0,0,'student@')).users[0].email,'student@example.test');
  await assert.rejects(dash(-1,0,''),/Invalid page/);
  const reviewed={title:'Cell Motility',generation:'reviewed',cards:[{id:'admin-id',noteId:'linked-note',type:'cloze',question:'Actin grows at the {{c1::plus end}}.',text:'Actin grows at the {{c1::plus end}}.',answer:'plus end',slide:1,status:'known',reviews:9,dueAt:123,sessionRetry:true}],slides:[{number:1,images:['crop']}],media:{crop:'data:image/jpeg;base64,AAAA'}};
  const deliver=async(id=ID)=>db.query('select public.deliver_study_submission($1,$2::jsonb,$3,$4) result',[id,JSON.stringify(reviewed),'Molecular Biology of the Cell','LS5001']);
  await login(C);await assert.rejects(deliver(),/Admin access required/);
  await login(B);
  const workspace={lectureId:'__workspace-settings',cards:[],_workspace:{modules:{pathobiology:{id:'pathobiology',name:'Pathobiology',code:'LS5009',deleted:true,_at:1},'custom-old':{id:'custom-old',name:'Other module',code:'OTHER',deleted:false,_at:1}},lectures:{old:{deleted:true,_at:1}}}};
  await db.query('select public.save_study_deck($1,$2::jsonb,0)',['__workspace-settings',JSON.stringify(workspace)]);
  await login(A);const deliveredId=(await deliver()).rows[0].result;assert.equal(deliveredId,'submission-'+ID);
  assert.equal((await db.query('select * from public.study_decks where lecture_id=$1',[deliveredId])).rows.length,0,'admin delivery is not added to admin account');
  await assert.rejects(deliver(),/already has a delivered deck/);await assert.rejects(deliver('cccccccc-cccc-4ccc-8ccc-cccccccccccc'),/Submission not found/);
  await login(B);const delivered=(await db.query('select payload from public.study_decks where lecture_id=$1',[deliveredId])).rows[0].payload;
  assert.equal(delivered.title,'Cell Motility');assert.ok(delivered.moduleId.startsWith('custom-'));assert.equal(delivered.cards[0].status,'new');assert.notEqual(delivered.cards[0].id,'admin-id');assert.equal(delivered.cards[0].reviews,undefined);assert.equal(delivered.cards[0].dueAt,undefined);assert.equal(delivered.cards[0].sessionRetry,undefined);assert.deepEqual(delivered.media,reviewed.media);
  let recipientWorkspace=(await db.query("select payload,revision from public.study_decks where lecture_id='__workspace-settings'")).rows[0];
  assert.equal(recipientWorkspace.payload._workspace.modules[delivered.moduleId].code,'LS5001');assert.deepEqual(recipientWorkspace.payload._workspace.lectures,workspace._workspace.lectures);assert.deepEqual(recipientWorkspace.payload._workspace.modules['custom-old'],workspace._workspace.modules['custom-old']);assert.equal(recipientWorkspace.revision,2);
  await upload(B,ORPHAN);await submit(ORPHAN);await login(A);await deliver(ORPHAN);
  await login(B);const second=(await db.query('select payload from public.study_decks where lecture_id=$1',['submission-'+ORPHAN])).rows[0].payload;assert.equal(second.moduleId,delivered.moduleId,'second lecture reuses recipient module');
  recipientWorkspace=(await db.query("select payload from public.study_decks where lecture_id='__workspace-settings'")).rows[0].payload;assert.equal(Object.keys(recipientWorkspace._workspace.modules).length,3);
  const third='cccccccc-cccc-4ccc-8ccc-cccccccccccc';await upload(B,third);await submit(third);
  await db.query("update public.study_decks set payload=jsonb_set(payload,'{cards,0,reviews}','5') where lecture_id=$1",[deliveredId]);
  await login(A);await assert.rejects(deliver(),/already has a delivered deck/);
  await db.query('select public.deliver_study_submission($1,$2::jsonb,$3,$4)',[third,JSON.stringify(reviewed),'Pathobiology','LS5009']);
  await login(B);const thirdDeck=(await db.query('select payload from public.study_decks where lecture_id=$1',['submission-'+third])).rows[0].payload;
  assert.ok(thirdDeck.moduleId.startsWith('custom-'),'delivery creates a new module when the matching default module is deleted');
  assert.equal((await db.query("select payload from public.study_decks where lecture_id='__workspace-settings'")).rows[0].payload._workspace.modules.pathobiology.deleted,true,'existing deleted module stays deleted');
  assert.equal((await db.query('select payload from public.study_decks where lecture_id=$1',[deliveredId])).rows[0].payload.cards[0].reviews,5,'duplicate delivery preserves student reviews');
  assert.equal((await db.query('select status from public.lecture_submissions where id=$1',[ID])).rows[0].status,'completed');
  await login(C);assert.equal((await db.query('select * from public.study_decks where lecture_id=$1',[deliveredId])).rows.length,0,'other accounts cannot access delivered slides or cards');
  const view=async(owner=B,lecture=null)=>(await db.query('select public.study_admin_view_account($1,$2) result',[owner,lecture])).rows[0].result;
  await assert.rejects(view(),/Admin access required/);await assert.rejects(db.query('select public.study_admin_prepared_decks()'),/Admin access required/);await assert.rejects(db.query('select * from public.study_prepared_decks'),/permission denied/);
  await db.exec('reset role;');
  const before=(await db.query('select user_id,lecture_id,payload,revision,updated_at from public.study_decks order by user_id,lecture_id')).rows;
  await login(A);const overview=await view();assert.equal(overview.account.email,'student@example.test');assert.ok(overview.workspace.modules[delivered.moduleId]);assert.equal(overview.lectures.find(l=>l.lecture_id===deliveredId).studied_count,1);
  assert.equal((await view(B,deliveredId)).deck.cards[0].reviews,5);await assert.rejects(view(C,deliveredId),/Lecture not found/);await assert.rejects(view(B,'__workspace-settings'),/Choose a lecture/);
  await view(A);await db.exec('reset role;');assert.deepEqual((await db.query('select user_id,lecture_id,payload,revision,updated_at from public.study_decks order by user_id,lecture_id')).rows,before,'inspection does not change payload, revision or update timestamps');
  await db.exec('reset role;');
  await db.query("insert into public.study_prepared_decks values('ls5001-cell-motility','LS5001 - Cell motility_7623612.pdf','Cell Motility','Molecular Biology of the Cell','LS5001',$1::jsonb)",[JSON.stringify(reviewed)]);
  await db.query("insert into public.study_prepared_decks values('ls5001-intracellular-trafficking','LS5001 - Intracellular Trafficking _7623619..pdf','Trafficking','Molecular Biology of the Cell','LS5001',$1::jsonb)",[JSON.stringify({...reviewed,title:'Trafficking'})]);
  await login(A);const catalog=(await db.query('select public.study_admin_prepared_decks() result')).rows[0].result;assert.equal(catalog.length,2);assert.equal(catalog[0].payload,undefined);assert.equal(catalog[0].card_count,1);
  await assert.rejects(db.query('select public.deliver_prepared_study_submission($1,$2)',[ID,'ls5001-cell-motility']),/does not match/);
  await db.exec('reset role;');
  const auto=readFileSync(new URL('../supabase/auto-deliver-ls5001.sql',import.meta.url),'utf8');
  await db.exec('begin;');await db.exec(auto);await db.exec('commit;');
  await db.query("update public.lecture_submissions set file_name='LS5001 - Cell motility_7623612.pdf' where id=$1",[ID]);
  await db.query("update public.lecture_submissions set file_name='LS5001 - Intracellular Trafficking _7623619..pdf' where id=$1",[ORPHAN]);
  await db.exec('begin;');await db.exec(auto);await db.exec('commit;');
  await login(A);await assert.rejects(db.query('select public.deliver_prepared_study_submission($1,$2)',[ID,'ls5001-cell-motility']),/already has a delivered deck/);assert.equal((await view(B,deliveredId)).deck.cards[0].reviews,5);
  await db.exec('reset role;');
  await db.query("update public.lecture_submissions set file_name='already-delivered.pdf' where id in ($1,$2)",[ID,ORPHAN]);
  const freshMotility='dddddddd-dddd-4ddd-8ddd-dddddddddddd',freshTrafficking='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
  for(const [id,file] of [[freshMotility,'LS5001 - Cell motility_7623612.pdf'],[freshTrafficking,'LS5001 - Intracellular Trafficking _7623619..pdf']])await db.query("insert into public.lecture_submissions(id,user_id,title,file_name,object_path,file_size) values($1,$2,$3,$3,$4,123)",[id,B,file,id+'/source.pdf']);
  await db.query("update public.lecture_submissions set file_name='LS5001 - Cell motility_7623612.pdf' where id=$1",[ID]);
  await db.exec('begin;');await db.exec(auto);await db.exec('commit;');assert.equal((await db.query('select * from public.study_decks where lecture_id=$1',['submission-'+freshMotility])).rows.length,0,'ambiguous source filenames do not assign decks');
  await db.query("update public.lecture_submissions set file_name='already-delivered.pdf' where id=$1",[ID]);
  await db.query('update public.lecture_submissions set user_id=$1 where id=$2',[C,freshTrafficking]);
  await db.exec('begin;');await db.exec(auto);await db.exec('commit;');assert.equal((await db.query('select * from public.study_decks where lecture_id=$1',['submission-'+freshMotility])).rows.length,0,'different senders require explicit inbox selection');
  await db.query('update public.lecture_submissions set user_id=$1 where id=$2',[B,freshTrafficking]);
  if(process.env.ADMIN_SETUP_SQL)await db.exec(readFileSync(process.env.ADMIN_SETUP_SQL,'utf8'));else{await db.exec('begin;');await db.exec(auto);await db.exec('commit;')}
  await login(A);const installedMotility=(await view(B,'submission-'+freshMotility)).deck,installedTrafficking=(await view(B,'submission-'+freshTrafficking)).deck;
  assert.equal(installedMotility.moduleId,installedTrafficking.moduleId);assert.ok(installedMotility.cards.every(c=>c.status==='new'));assert.equal((await view(B,deliveredId)).deck.cards[0].reviews,5);
  if(process.env.ADMIN_SETUP_SQL){assert.equal(installedMotility.cards.length,71);assert.equal(installedTrafficking.cards.length,103);assert.ok(Object.keys(installedMotility.media).length>10)}
  await db.exec('reset role;set role anon;');await assert.rejects(db.query('select public.is_study_admin()'),/permission denied/);await assert.rejects(dash(),/permission denied/);await assert.rejects(submit(),/permission denied/);await assert.rejects(view(),/permission denied/);await assert.rejects(db.query('select public.study_admin_prepared_decks()'),/permission denied/);
 }finally{await db.close()}
});
