import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333';
const ID='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',ORPHAN='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
test('admin codes, user summaries and slide files enforce server-side permissions',async()=>{
 const db=new PGlite();
 try{
  await db.exec(`create role anon;create role authenticated;create schema auth;
   create table auth.users(id uuid primary key,email text,created_at timestamptz default now(),last_sign_in_at timestamptz);
   insert into auth.users(id,email) values('${A}','admin@example.test'),('${B}','student@example.test'),('${C}','other@example.test');
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;
   create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
   create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb,unique(bucket_id,name));
   alter table storage.objects enable row level security;grant usage on schema storage to authenticated;
   grant select,insert,delete on storage.objects to authenticated;
   create function storage.foldername(name text) returns text[] language sql immutable as $$select string_to_array(name,'/')$$;
   grant execute on function storage.foldername(text) to authenticated;`);
  await db.exec(readFileSync(new URL('../supabase/setup.sql',import.meta.url),'utf8'));
  const sql=readFileSync(new URL('../supabase/admin.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
  const code=(await db.query(readFileSync(new URL('../supabase/admin-code.sql',import.meta.url),'utf8'))).rows[0].admin_unlock_code;
  assert.ok(code.length>60);
  const login=async id=>db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${id}';`);
  const isAdmin=async()=>(await db.query('select public.is_study_admin() result')).rows[0].result;
  const dash=async(...args)=>(await db.query('select public.study_admin_dashboard($1,$2,$3) result',args.length?args:[0,0,''])).rows[0].result;
  const upload=async(owner,id=ID)=>db.query("insert into storage.objects(bucket_id,name,metadata) values('lecture-submissions',$1,'{\"size\":123}')",[`${owner}/${id}/source.pdf`]);
  const submit=async(id=ID,size=123)=>db.query("select public.submit_study_lecture($1,'Lecture','pathobiology','Please make cards','lecture.pdf',$2,'pdf')",[id,size]);
  await login(B);assert.equal(await isAdmin(),false);
  await assert.rejects(db.query('select * from public.study_admin_codes'),/permission denied/);
  await assert.rejects(db.query('insert into public.study_admins(user_id) values($1)',[B]),/permission denied/);
  await assert.rejects(db.query('select public.unlock_study_admin($1)',['incorrect-but-long-enough-code']),/Invalid or expired/);
  await assert.rejects(dash(),/Admin access required/);
  await assert.rejects(upload(A),/row-level security/);
  await assert.rejects(submit(),/Upload the complete/);
  await upload(B);await assert.rejects(submit(ID,122),/Upload the complete/);await submit();
  assert.equal((await db.query('select * from public.lecture_submissions')).rows.length,1);
  await assert.rejects(db.query('update public.lecture_submissions set status=\'completed\''),/permission denied/);
  await login(C);assert.equal((await db.query('select * from public.lecture_submissions')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
  await assert.rejects(db.query("select public.review_study_submission($1,'completed','Hello')",[ID]),/Admin access required/);
  await login(A);await db.query('select public.unlock_study_admin($1)',[code]);assert.equal(await isAdmin(),true);
  await db.query('select public.save_study_deck($1,$2::jsonb,0)',['test',JSON.stringify({lectureId:'test',cards:[{id:'secret',question:'Private question',reviews:1},{id:'bad',reviews:'bad'},{id:'overflow',reviews:'9999999999999999999999999999'}]})]);
  await db.query("insert into public.study_decks(user_id,lecture_id,payload) values($1,'malformed','{\"cards\":{\"not\":\"an array\"}}')",[A]);
  const data=await dash();assert.equal(data.user_count,3);assert.equal(data.submissions[0].sender_email,'student@example.test');assert.equal(data.users.find(u=>u.id===A).studied_cards,1);
  assert.equal(JSON.stringify(data).includes('Private question'),false);assert.equal('payload' in data.users[0],false);
  assert.equal((await db.query('select * from storage.objects')).rows.length,1);
  await assert.rejects(db.query("select public.review_study_submission($1,'invalid','Hello')",[ID]),/Invalid review/);
  await db.query("select public.review_study_submission($1,'completed','Deck ready soon')",[ID]);
  await login(B);await assert.rejects(db.query('select public.unlock_study_admin($1)',[code]),/Invalid or expired/);
  const reply=(await db.query('select * from public.lecture_submissions')).rows[0];assert.equal(reply.status,'completed');assert.equal(reply.admin_reply,'Deck ready soon');
  assert.equal((await db.query('delete from storage.objects')).affectedRows,0,'submitted files cannot be removed by sender');
  await upload(B,ORPHAN);assert.equal((await db.query('delete from storage.objects')).affectedRows,1,'failed unsubmitted uploads can be cleaned up');
  await assert.rejects(db.query("select public.submit_study_lecture($1,'Lecture','','','bad.html',123,'pdf')",[ORPHAN]),/Invalid slide submission/);
  await db.exec('reset role;');
  for(let i=0;i<26;i++)await db.query('insert into auth.users(id,email) values(gen_random_uuid(),$1)',[`page${i}@example.test`]);
  await db.query("insert into public.study_admin_codes(code_hash,expires_at) values(sha256(convert_to($1,'UTF8')),now()-interval '1 second')",['expired-code-long-enough']);
  await login(C);await assert.rejects(db.query('select public.unlock_study_admin($1)',['expired-code-long-enough']),/Invalid or expired/);
  await login(A);assert.equal((await dash(0,0,'page')).users.length,25);assert.equal((await dash(1,0,'page')).users.length,1);assert.equal((await dash(0,0,'student@')).users[0].email,'student@example.test');
  await assert.rejects(dash(-1,0,''),/Invalid page/);
  await db.exec('reset role;set role anon;');await assert.rejects(db.query('select public.is_study_admin()'),/permission denied/);await assert.rejects(dash(),/permission denied/);await assert.rejects(submit(),/permission denied/);
 }finally{await db.close()}
});
