import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {PGlite} from '@electric-sql/pglite';import {recordAttempt} from '../src/review-stats.js';
test('shared statistics requires login, three accounts and matching canonical prompts; returns aggregates only',async()=>{const db=new PGlite();try{
const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333'];await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);insert into auth.users values ${ids.map(id=>`('${id}')`).join(',')};create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);await db.exec(readFileSync(new URL('../supabase/setup.sql',import.meta.url),'utf8'));const sql=readFileSync(new URL('../supabase/statistics.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);assert.equal((await db.query('select count(*)::int n from public.study_statistics_catalog')).rows[0].n,850);
const lecture=JSON.parse(readFileSync(new URL('../public/viruses/deck.json',import.meta.url),'utf8'));const login=async id=>db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${id}'`);const report=async()=>(await db.query('select public.study_statistics_dashboard() data')).rows[0].data;
for(let i=0;i<3;i++){await login(ids[i]);const d={...lecture,cards:[lecture.cards[0]]};recordAttempt(d,d.cards[0],i===0?'again':i===1?'hard':'good');recordAttempt(d,d.cards[0],'easy');await db.query('select public.save_study_deck($1,$2::jsonb,0)',['viruses',JSON.stringify(d)]);if(i<2)assert.deepEqual((await report()).cards,[])}
const cards=(await report()).cards;assert.equal(cards.length,1);assert.equal(cards[0].correct,4);assert.equal(cards[0].incorrect,1);assert.equal(cards[0].partial,1);assert.equal('user_id' in cards[0],false);assert.equal('email' in cards[0],false);assert.equal('events' in cards[0],false);assert.equal((await db.query('select * from public.study_decks')).rows.length,1);await assert.rejects(db.query('select * from public.study_statistics_catalog'),/permission denied/);
const custom={lectureId:'private',title:'Private notes',cards:[{id:'private',text:'Private answer',slide:1}]};recordAttempt(custom,custom.cards[0],'good');await db.query('select public.save_study_deck($1,$2::jsonb,0)',['private',JSON.stringify(custom)]);assert.equal((await report()).cards.length,1);
const edited={...lecture,cards:[{...lecture.cards[0],text:'Private edited wording',answer:'Private answer'}]};for(let i=0;i<6;i++)recordAttempt(edited,edited.cards[0],'good');await db.query('select public.save_study_deck($1,$2::jsonb,1)',['viruses',JSON.stringify(edited)]);assert.deepEqual((await report()).cards,[],'private edits cannot qualify as canonical shared attempts');const restored={...lecture,cards:[lecture.cards[0]]};recordAttempt(restored,restored.cards[0],'good');recordAttempt(restored,restored.cards[0],'easy');await db.query('select public.save_study_deck($1,$2::jsonb,2)',['viruses',JSON.stringify(restored)]);assert.equal((await report()).cards.length,1);
await login(ids[0]);await db.query("update public.study_decks set payload=jsonb_set(payload,'{_reviewEvents}','{}'::jsonb) where lecture_id='viruses'");assert.deepEqual((await report()).cards,[]);await db.exec('reset role;set role anon');await assert.rejects(report(),/permission denied/);
}finally{await db.close()}});
