import test from 'node:test';import assert from 'node:assert/strict';import {focusSettings,focusSelection,cardDifficulty,cardImportance} from '../src/study-focus.js';import {stampChanges,mergeDecks} from '../src/sync-model.js';
test('difficulty follows ratings and personal overrides; unstudied cards start medium',()=>{assert.equal(cardDifficulty({}),'medium');assert.equal(cardDifficulty({lastRating:'again'}),'hard');assert.equal(cardDifficulty({lastRating:'hard'}),'hard');assert.equal(cardDifficulty({lastRating:'good',lapses:7}),'medium');assert.equal(cardDifficulty({lastRating:'easy'}),'easy');assert.equal(cardDifficulty({lastRating:'again',difficulty:'easy'}),'easy');assert.equal(cardImportance({text:'DNA replication'}),'important');assert.equal(cardImportance({text:'Chamberland filter discovery'}),'standard');assert.equal(cardImportance({text:'DNA replication',importance:'standard'}),'standard')});
test('importance and difficulty combine, with a bounded session and stable card data',()=>{
 const cards=Array.from({length:100},(_,i)=>({id:String(i),importance:i<80?'important':'standard',difficulty:'hard',dueAt:999,reviews:3}));const before=structuredClone(cards);let result=focusSelection(cards,{importance:'important',difficulty:'hard',cram:false});assert.equal(result.matched,80);assert.equal(result.cards.length,50);assert.equal(focusSelection(cards,{importance:'standard',difficulty:'hard',cram:false}).cards.length,20);assert.equal(focusSelection(cards,{importance:'all',difficulty:'easy',cram:false}).cards.length,0);assert.deepEqual(cards,before);
 for(const [difficulty,limit] of [['easy',10],['medium',25],['hard',50]])assert.equal(focusSelection(cards.map(c=>({...c,difficulty})),{importance:'all',difficulty,cram:false}).cards.length,limit);
 assert.equal(focusSelection(cards,focusSettings({})).cards.length,100);
});
test('cram shows only important cards, harder first, including scheduled cards; filters persist independently of review sync',()=>{
 const cards=[{id:'easy',difficulty:'easy',importance:'important',dueAt:999},{id:'support',difficulty:'hard',importance:'standard'},{id:'hard',difficulty:'hard',importance:'important',dueAt:999}];const selection=focusSelection(cards,{importance:'all',difficulty:'any',cram:true});assert.deepEqual(selection.cards.map(c=>c.id),['hard','easy']);assert.equal(selection.limit,25);
 const original=stampChanges(null,{lectureId:'deck',cards:[{id:'a',question:'Q',reviews:0}]},1);const prefs=stampChanges(original,{...original,studyFocus:{importance:'important',difficulty:'hard',cram:true},cards:[{...original.cards[0],importance:'important'}]},2);const studied=stampChanges(original,{...original,cards:[{...original.cards[0],reviews:4,lastRating:'hard',dueAt:100}]},3);const merged=mergeDecks(prefs,studied);assert.equal(merged.studyFocus.cram,true);assert.equal(merged.cards[0].importance,'important');assert.equal(merged.cards[0].reviews,4);assert.equal(merged.cards[0].dueAt,100);
});
