const {chromium}=require('playwright'),assert=require('node:assert/strict');
const {fixture,A}=require('./check-accounts.cjs');const {navigate}=require('./navigation-helper.cjs');
function lecturePDF(){
 const stream='BT /F1 16 Tf 30 180 Td (Mitochondria produce ATP.) Tj ET';
 const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 420 240] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];
 let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf);
}
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});try{for(const phone of [false,true]){
 const c=await browser.newContext({viewport:phone?{width:360,height:640}:{width:1280,height:800},hasTouch:phone,isMobile:phone});
 const errors=[],external=[];const submission={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',user_id:A,title:'Submitted energy lecture',module_id:'pathobiology',file_name:'energy.pdf',file_size:lecturePDF().length,object_path:`${A}/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/source.pdf`,status:'received',created_at:new Date().toISOString(),sender_email:'student@example.test'};
 await fixture(c,{socialHandler:async name=>{if(name==='is_study_admin')return {data:true};if(name==='study_admin_dashboard')return {data:{users:[],user_count:0,submissions:[submission],submission_count:1,pending_count:1}}}});
 await c.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.__copiedPrompt=text}},configurable:true}));
 await c.route('**/storage/v1/object/**',r=>r.fulfill({body:lecturePDF(),contentType:'application/pdf'}));c.on('request',r=>{if(/chatgpt.com|api.openai.com/.test(r.url()))external.push(r.url())});
 const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4189/revise-1/');await p.locator('#flip').waitFor();await navigate(p,'account');await p.locator('#account-email').fill('a@example.test');await p.locator('#account-password').fill('fixture-password');await p.locator('button[value="signin"]').click();await p.locator('#admin-mode').waitFor();await p.locator('#admin-mode').check();await navigate(p,'admin');await p.locator('[data-chatgpt-submission]').waitFor();await p.locator('[data-chatgpt-submission]').click();assert.equal(await p.locator('#chatgpt-title').inputValue(),submission.title);assert.equal(await p.locator('#chatgpt-module').inputValue(),'pathobiology');
 await p.locator('#chatgpt-copy').click();assert.match(await p.evaluate(()=>window.__copiedPrompt),/Submitted energy lecture/);assert.match(await p.evaluate(()=>window.__copiedPrompt),/LS5009/);assert.equal(await p.locator('#chatgpt-tools a[href="https://chatgpt.com/"]').getAttribute('target'),'_blank');
 await p.locator('#chatgpt-json').fill('not json');await p.locator('#chatgpt-preview').click();await p.locator('#chatgpt-tools [role="alert"]').waitFor();assert.equal(await p.locator('#chatgpt-import').isDisabled(),true);
 const deck={title:'Energy',cards:[{type:'cloze',text:'{{c1::Mitochondria}} produce {{c2::ATP}}.',topic:'Cellular energy',slide:1,importance:'important',difficulty:'medium'}]};await p.locator('#chatgpt-json').fill('```json\n'+JSON.stringify(deck)+'\n```');await p.locator('#chatgpt-preview').click();assert.match(await p.locator('.chatgpt-preview').innerText(),/2 cards ready/);await p.locator('#chatgpt-import').click();await p.locator('#flip').waitFor();await p.locator('#flip').click();await p.locator('#flip .slide-pictures img').waitFor();assert.equal(await p.locator('#flip .slide-pictures img').count(),1);
 const stored=await p.evaluate(async()=>{const db=await new Promise(resolve=>{const q=indexedDB.open('micro-flashcards',1);q.onsuccess=()=>resolve(q.result)});return new Promise(resolve=>{const q=db.transaction('decks').objectStore('decks').get('user:11111111-1111-4111-8111-111111111111:current');q.onsuccess=()=>resolve(q.result)})});assert.equal(stored.cards.length,2);assert.equal(stored.moduleId,'pathobiology');assert.equal(stored.title,submission.title);assert.equal(stored.slides.length,1);assert.equal(stored.cards[0].status,'new');assert.ok(stored.media['pdf-1'].startsWith('data:image/jpeg;base64,'));assert.equal(stored.generation,'chatgpt');
 await navigate(p,'admin');await p.locator('#chatgpt-clear-source').click();await p.locator('#chatgpt-title').fill('Second lecture');await p.locator('#chatgpt-json-file').setInputFiles({name:'chuds-deck.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(deck))});await p.locator('.chatgpt-preview').waitFor();assert.match(await p.locator('.chatgpt-preview').innerText(),/text cards/);await p.locator('#chatgpt-title').fill('Changed title');assert.equal(await p.locator('#chatgpt-import').isDisabled(),true);await p.locator('#chatgpt-preview').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await p.locator('#chatgpt-import').click();await p.locator('#flip').waitFor();await p.locator('#lecture-switch option').filter({hasText:'Changed title'}).waitFor({state:'attached'});assert.equal(await p.locator('#lecture-switch option').filter({hasText:'Changed title'}).count(),1);assert.equal(await p.locator('#lecture-switch option').filter({hasText:submission.title}).count(),1,'imports add decks without replacing the first one');await p.reload();await p.locator('#flip').waitFor();await p.locator('#lecture-switch option').filter({hasText:'Changed title'}).waitFor({state:'attached'});assert.equal(await p.locator('#lecture-switch option').filter({hasText:'Changed title'}).count(),1);assert.deepEqual(errors,[]);assert.deepEqual(external,[],'no automatic ChatGPT/API requests');await c.close();
 }console.log('PASS: desktop/phone prompt copying, submission selection, cloze preview, JSON paste/file imports, source-picture attachment, fresh schedules, module grouping, reload persistence and no API calls.')}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
