const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});try{
for(const viewport of [{width:1366,height:900},{width:360,height:640},{width:844,height:390}]){
 const c=await b.newContext({viewport});await c.route('**/account-config.json',r=>r.fulfill({json:{supabaseUrl:'',supabasePublishableKey:''}}));const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.ACCOUNT_TEST_URL||'http://127.0.0.1:4189/revise-1/');await p.locator('#welcome-start').waitFor();
 assert.match(await p.locator('#welcome-title').innerText(),/Welcome friends to my\s+goofy ahh revision app/);assert.equal(await p.locator('.dog-welcome').evaluate(el=>el.matches(':modal')),true);await p.locator('.welcome-mascot').evaluate(i=>i.decode());assert.equal(await p.locator('.welcome-dog').first().evaluate(el=>getComputedStyle(el).animationName),'dog-float');
 await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.welcome-dog').first().evaluate(el=>getComputedStyle(el).animationName),'none');if(viewport.width===360)await p.screenshot({path:'/tmp/chuds-welcome-phone.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await p.locator('#welcome-start').click();await p.locator('.dog-welcome').waitFor({state:'detached'});await p.locator('#flip').waitFor();await p.locator('#flip').click();await p.locator('#good').click();await p.reload();await p.locator('#flip').waitFor();assert.equal(await p.locator('.dog-welcome').count(),0,'no repeat during same tab session');
 await p.evaluate(()=>sessionStorage.removeItem('chuds-welcome-seen-v1'));await p.reload();await p.locator('#welcome-start').waitFor();await p.keyboard.press('Escape');await p.locator('.dog-welcome').waitFor({state:'detached'});assert.deepEqual(errors,[]);await c.close();
}console.log('PASS: welcome message, animated dog photos, reduced motion, desktop/phone/landscape, dismissal and Escape, once-per-tab behavior, and studying afterwards.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
