const {chromium}=require('playwright'),assert=require('node:assert/strict');const {fixture}=require('./check-accounts.cjs');const {navigate}=require('./navigation-helper.cjs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});try{
for(const phone of [false,true]){
 const context=await browser.newContext({viewport:phone?{width:360,height:640}:{width:1366,height:900},isMobile:phone,hasTouch:phone});await fixture(context);await context.addInitScript(()=>{
 window.voiceCalls=[];window.audioCancels=0;class Utterance{constructor(text){this.text=text}}class Recognition{start(){window.testRecognition=this}abort(){this.aborted=true}}
 Object.defineProperty(window,'SpeechRecognition',{value:Recognition,configurable:true});Object.defineProperty(window,'SpeechSynthesisUtterance',{value:Utterance,configurable:true});Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[{lang:'en-GB',localService:true}],speak:u=>{window.voiceCalls.push(u.text);window.lastUtterance=u},cancel:()=>window.audioCancels++},configurable:true});
 });const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.ACCOUNT_TEST_URL||'http://127.0.0.1:4189/revise-1/');await page.locator('#flip').waitFor();assert.equal(await page.locator('#voice-practice').getAttribute('open'),null);await page.locator('#voice-practice summary').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#good').isDisabled(),true,'opening voice practice with the keyboard does not reveal the answer');
 await page.locator('#voice-read').click();const question=await page.locator('#flip h2').innerText();const said=await page.evaluate(()=>voiceCalls[0]);assert.equal(said.replace(/\s+/g,' ').trim(),question.replace(/\[\s*[.…]+\s*\]/g,' blank ').replace(/\s+/g,' ').trim());assert.equal(said.includes('{{c'),false,'cloze answer markup is never spoken');await page.locator('#voice-stop').click();assert.equal(await page.locator('#voice-stop').isDisabled(),true);
 await page.locator('#voice-dictate').click();assert.equal(await page.locator('#voice-dictate').getAttribute('aria-pressed'),'true');await page.evaluate(()=>testRecognition.onresult({results:[[{transcript:'My spoken answer'}]]}));assert.equal(await page.locator('#voice-transcript').inputValue(),'My spoken answer');await page.evaluate(()=>testRecognition.onend());await page.locator('#voice-auto').check();await page.locator(phone?'#phone-reveal-answer':'#flip').click();assert.equal(await page.locator('#voice-transcript').inputValue(),'My spoken answer');assert.equal((await page.evaluate(()=>voiceCalls)).length,2,'opted-in reveal reads the answer once');assert.ok((await page.evaluate(()=>voiceCalls[1])).includes((await page.locator('#flip h2').innerText()).trim()));
 if(phone){const r=await page.locator('#good').boundingBox();assert.ok(r.y+r.height<=640,'rating remains visible with expanded voice controls')}await page.locator('#good').click();assert.equal(await page.locator('#voice-transcript').inputValue(),'','new card clears dictation');
 await page.locator('#voice-dictate').click();await page.evaluate(()=>testRecognition.onerror({error:'not-allowed'}));await page.getByText(/Microphone access was denied/).waitFor();await page.locator('#voice-transcript').fill('Typed fallback');await navigate(page,'lectures');assert.equal(await page.evaluate(()=>lastUtterance?audioCancels>0:false),true);await navigate(page,'study');await page.locator('#voice-practice summary').click();await page.locator('#voice-practice summary').click();assert.equal(await page.locator('#voice-transcript').inputValue(),'','dictation is not retained after navigation');assert.deepEqual(errors,[]);await context.close();
}
const context=await browser.newContext();await fixture(context);await context.addInitScript(()=>{Object.defineProperty(window,'SpeechRecognition',{value:undefined,configurable:true});Object.defineProperty(window,'webkitSpeechRecognition',{value:undefined,configurable:true});Object.defineProperty(window,'speechSynthesis',{value:undefined,configurable:true})});const page=await context.newPage();await page.goto(process.env.ACCOUNT_TEST_URL||'http://127.0.0.1:4189/revise-1/');await page.locator('#flip').waitFor();await page.locator('#voice-practice summary').click();assert.equal(await page.locator('#voice-dictate').isDisabled(),true);assert.equal(await page.locator('#voice-read').isDisabled(),true);await page.locator('#voice-transcript').fill('Typing still works');
console.log('PASS: browser speech fixtures cover question/answer reading, opt-in audio replies, dictation, denied microphone and unsupported-browser fallbacks, clearing on navigation, and phone rating access.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
