const KEY='micro-appearance-v1';
const modes=[['light','☀','Light','Bright and clear'],['dark','☾','Dark','Gentler after hours'],['system','◐','Match device','Follow your phone or computer']];
const styles=[['forest','Forest','Calm greens','#73935d'],['ocean','Ocean','Cool blues','#4388b5'],['lavender','Lavender','Soft purples','#8d6bb7'],['rose','Rose','Warm pinks','#b96b84']];
export function appearanceSettings({render}){
 let value={mode:'system',style:'forest'},notice='';const system=matchMedia('(prefers-color-scheme: dark)');
 try{const saved=JSON.parse(localStorage.getItem(KEY));if(modes.some(m=>m[0]===saved?.mode))value.mode=saved.mode;if(styles.some(s=>s[0]===saved?.style))value.style=saved.style}catch{}
 function apply(){const root=document.documentElement;root.dataset.mode=value.mode==='system'?(system.matches?'dark':'light'):value.mode;root.dataset.style=value.style;root.style.colorScheme=root.dataset.mode;const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=getComputedStyle(root).getPropertyValue('--theme-bg').trim()||(root.dataset.mode==='dark'?'#151b18':'#f7f8f4')}
 function change(key,next){if(!(key==='mode'?modes:styles).some(v=>v[0]===next))return;value={...value,[key]:next};notice='';try{localStorage.setItem(KEY,JSON.stringify(value))}catch{notice='Your choice is applied, but this browser could not save it for next time.'}apply();render()}
 function html(){return `<section class="settings-workspace"><span class="eyebrow">MAKE THIS SPACE YOURS</span><h2>A look that helps you focus.</h2><p class="settings-intro">Choose your lighting and colours. Your preference stays saved on this browser, so each device can have its own look.</p>${notice?`<p role="status" class="notice">${notice}</p>`:''}<section class="workspace-panel"><h3>Appearance</h3><div class="appearance-modes" role="group" aria-label="Colour mode">${modes.map(([key,icon,label,description])=>`<button class="appearance-choice ${value.mode===key?'selected':''}" data-appearance-mode="${key}" aria-pressed="${value.mode===key}"><span class="appearance-icon" aria-hidden="true">${icon}</span><strong>${label}</strong><small>${description}</small></button>`).join('')}</div></section><section class="workspace-panel"><h3>Colour style</h3><div class="appearance-styles" role="group" aria-label="Colour style">${styles.map(([key,label,description,colour])=>`<button class="appearance-choice ${value.style===key?'selected':''}" data-appearance-style="${key}" aria-pressed="${value.style===key}"><span class="style-preview" style="--preview:${colour}"><i></i><i></i><i></i></span><strong>${label}</strong><small>${description}</small></button>`).join('')}</div></section><section class="workspace-panel appearance-preview"><span class="eyebrow">YOUR STUDY SPACE</span><h3>Small steps. Stronger recall.</h3><p>A little review each day builds <span class="cloze revealed">lasting understanding</span>.</p><div class="appearance-preview-actions"><span class="button primary">Ready to study</span><span class="button confident">Good · 1 day</span></div></section><button class="text-button" id="appearance-reset">Reset appearance to match device + Forest</button></section>`}
 function bind(){for(const [selector,key,prop]of [['[data-appearance-mode]','mode','appearanceMode'],['[data-appearance-style]','style','appearanceStyle']])document.querySelectorAll(selector).forEach(b=>b.onclick=()=>change(key,b.dataset[prop]));document.getElementById('appearance-reset')?.addEventListener('click',()=>{value.style='forest';change('mode','system')})}
 const onSystem=()=>{if(value.mode==='system'){apply();render()}};if(system.addEventListener)system.addEventListener('change',onSystem);else system.addListener(onSystem);window.addEventListener('storage',event=>{if(event.key!==KEY)return;try{const next=JSON.parse(event.newValue);value={mode:modes.some(m=>m[0]===next?.mode)?next.mode:'system',style:styles.some(s=>s[0]===next?.style)?next.style:'forest'};apply();render()}catch{}});
 apply();return {html,bind};
}
