import JSZip from 'jszip';
import './style.css';
const KEY='micro-deck-v1';
let deck=null;try{deck=JSON.parse(localStorage.getItem(KEY))}catch{}
let view='study',index=0,flipped=false,filter='all',search='',queue=[],busy=false,message='',editing=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(deck))}catch{message='Browser storage is full. Export your deck to keep it.'}};
const cards=()=>deck?.cards||[];
function resetQueue(){queue=cards().filter(c=>filter==='all'||c.status===filter).map(c=>c.id);index=0;flipped=false}
function current(){return cards().find(c=>c.id===queue[index])}
function render(){
 const all=cards(),known=all.filter(c=>c.status==='known').length,c=current();
 document.querySelector('#app').innerHTML=`<aside><a class="brand" href="#"><span class="brand-icon">✳</span> micro<span class="brand-dot">.</span></a><div class="workspace-label">YOUR WORKSPACE</div><button class="nav ${view==='study'?'active':''}" data-view="study">▱ <span>Study cards</span></button><button class="nav ${view==='library'?'active':''}" data-view="library">▦ <span>Card library</span><small>${all.length}</small></button><div class="aside-bottom"><div class="privacy-dot"></div><div>Made for your mind.<br><small>Stored only in this browser</small></div></div></aside>
 <main><header><span>MY LECTURES <span class="slash">/</span> <strong>Microorganisms</strong></span><button class="button subtle" id="import-top">＋ Import lecture</button></header><section class="content"><div class="eyebrow"><span></span> LIFE SCIENCES · LS5008 / LS5030</div><div class="title-row"><div><h1>Small organisms.<br>Big understanding.</h1><p class="subtitle">A little recall today. A lot more confidence tomorrow.</p></div><div class="micro-art" aria-hidden="true"><i></i><i></i><i></i><b>✳</b><span>THE MICRO WORLD</span></div></div>
 ${message?`<div role="status" class="notice">${esc(message)}</div>`:''}
 <div class="stats"><div><span class="stat-icon">▦</span><div><strong>${all.length}</strong><small>Flashcards</small></div></div><div><span class="stat-icon green">✓</span><div><strong>${known}</strong><small>Confident</small></div></div><div><span class="stat-icon orange">↻</span><div><strong>${all.filter(c=>c.status==='review').length}</strong><small>To revisit</small></div></div><div class="progress-stat"><div><small>YOUR PROGRESS</small><strong>${all.length?Math.round(known/all.length*100):0}%</strong></div><div class="progress"><i style="width:${all.length?known/all.length*100:0}%"></i></div></div></div>
 ${!deck?`<section class="import-panel"><div class="upload-icon">↥</div><span class="eyebrow">YOUR LECTURE, READY TO LEARN</span><h2>Bring your notes to life.</h2><p>Open <strong>Revisiting microorganisms</strong> to create a personal<br class="desktop"> flashcard deck from your PowerPoint slides.</p><button class="button primary" id="upload">${busy?'Reading your lecture…':'Choose lecture file'} <span>↗</span></button><small>POWERPOINT (.PPTX) OR EXPORTED DECK (.JSON)</small><div class="local-note">♧ Your lecture stays on your device. No account needed.</div></section>`:view==='study'?`<div class="study-toolbar"><div class="tabs"><button data-filter="all" class="${filter==='all'?'selected':''}">All cards</button><button data-filter="review" class="${filter==='review'?'selected':''}">To revisit</button><button data-filter="new" class="${filter==='new'?'selected':''}">Unstudied</button></div><button class="text-button" id="shuffle">⇄ Shuffle</button></div>
 ${c?`<div class="card-meta"><span>SLIDE ${c.slide} <span>·</span> ${esc(c.topic)}</span><span>${index+1} / ${queue.length}</span></div><button class="flashcard ${flipped?'flipped':''}" id="flip"><span class="card-label">${flipped?'THE ANSWER':'QUICK RECALL'}</span><h2>${esc(flipped?c.answer:c.question)}</h2><span class="flip-hint">⤾ ${flipped?'Click to see question':'Click to reveal answer'} <kbd>Space</kbd></span></button><div class="rating"><button class="button review" id="review" ${!flipped?'disabled':''}>↻ Still learning <kbd>1</kbd></button><button class="button confident" id="known" ${!flipped?'disabled':''}>✓ Got it <kbd>2</kbd></button></div><div class="card-navigation"><button id="prev" ${index===0?'disabled':''}>← Previous</button><span>Take your time. Understanding beats speed.</span><button id="next" ${index>=queue.length-1?'disabled':''}>Next →</button></div>`:`<div class="empty-state"><span>✳</span><h2>${queue.length?'Session complete. Nice work.':'A clean slate.'}</h2><p>${queue.length?'Your progress is saved. Revisit the deck whenever you’re ready.':'There are no cards in this group.'}</p><button class="button primary" id="restart">Study again</button></div>`}`:
 `<div class="library-toolbar"><input id="search" placeholder="Search questions, answers, or topics…" value="${esc(search)}"><button class="button subtle" id="add">＋ Add card</button><button class="button subtle" id="export">↓ Export</button></div><div class="library">${all.filter(c=>[c.question,c.answer,c.topic].join(' ').toLowerCase().includes(search.toLowerCase())).map(c=>`<article><div><span class="eyebrow">SLIDE ${c.slide} · ${esc(c.topic)}</span><h3>${esc(c.question)}</h3><p>${esc(c.answer)}</p></div><button class="text-button" data-edit="${c.id}">Edit ↗</button></article>`).join('')||'<p>No matching cards.</p>'}</div>`}
 <footer><span>✳ Built around your lecture.</span><span>${deck?'Draft cards from slide text · Review in the library':'Read. Recall. Repeat.'}</span></footer></section></main><input type="file" id="file" accept=".pptx,.json" hidden>
 ${editing?`<div class="modal-backdrop"><form id="edit-form" class="modal"><h2>${editing.id?'Edit flashcard':'New flashcard'}</h2><label>Topic<input name="topic" value="${esc(editing.topic)}" required></label><label>Question<textarea name="question" required>${esc(editing.question)}</textarea></label><label>Answer<textarea name="answer" required>${esc(editing.answer)}</textarea></label><div><button type="button" class="button subtle" id="cancel">Cancel</button>${editing.id?'<button type="button" class="button review" id="delete">Delete</button>':''}<button class="button primary">Save card</button></div></form></div>`:''}`;
 bind();
}
function bind(){
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
 for(const id of ['upload','import-top'])document.getElementById(id)?.addEventListener('click',()=>{if(!busy)document.getElementById('file').click()});
 document.getElementById('file').onchange=e=>importFile(e.target.files[0]);
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;resetQueue();render()});
 document.getElementById('flip')?.addEventListener('click',()=>{flipped=!flipped;render()});
 for(const status of ['review','known'])document.getElementById(status)?.addEventListener('click',()=>rate(status));
 for(const [id,step] of [['prev',-1],['next',1]])document.getElementById(id)?.addEventListener('click',()=>{index+=step;flipped=false;render()});
 document.getElementById('restart')?.addEventListener('click',()=>{resetQueue();render()});
 document.getElementById('shuffle')?.addEventListener('click',()=>{for(let i=queue.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[queue[i],queue[j]]=[queue[j],queue[i]]}index=0;flipped=false;render()});
 document.getElementById('search')?.addEventListener('input',e=>{search=e.target.value;const pos=e.target.selectionStart;render();const input=document.getElementById('search');input.focus();input.setSelectionRange(pos,pos)});
 document.getElementById('export')?.addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(deck,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='micro-flashcards.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
 document.getElementById('add')?.addEventListener('click',()=>{editing={topic:'My notes',question:'',answer:'',slide:0};render()});
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing={...cards().find(c=>c.id===b.dataset.edit)};render()});
 document.getElementById('cancel')?.addEventListener('click',()=>{editing=null;render()});
 document.getElementById('delete')?.addEventListener('click',()=>{deck.cards=cards().filter(c=>c.id!==editing.id);editing=null;save();resetQueue();render()});
 document.getElementById('edit-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const next={...editing,topic:f.get('topic').trim(),question:f.get('question').trim(),answer:f.get('answer').trim()};if(!next.question||!next.answer||!next.topic)return;if(next.id)deck.cards=cards().map(c=>c.id===next.id?next:c);else deck.cards.push({...next,id:crypto.randomUUID(),status:'new'});editing=null;save();resetQueue();render()});
}
function rate(status){const c=current();if(!c||!flipped)return;c.status=status;save();index++;flipped=false;render()}
async function importFile(file){if(!file)return;if(deck&&!confirm('Replace your current deck? Export it first if you want to keep a copy.'))return;busy=true;message='';render();try{
 let next;
 if(file.name.toLowerCase().endsWith('.json')){next=JSON.parse(await file.text());if(!Array.isArray(next.cards)||!next.cards.length||!next.cards.every(c=>typeof c.question==='string'&&typeof c.answer==='string'))throw Error('This file is not a valid flashcard deck.');next.cards=next.cards.map(c=>({...c,id:crypto.randomUUID(),topic:String(c.topic||'Lecture'),slide:Number(c.slide)||0,status:['new','review','known'].includes(c.status)?c.status:'new'}))}
 else if(file.name.toLowerCase().endsWith('.pptx')){const zip=await JSZip.loadAsync(file);const names=Object.keys(zip.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n)).sort((a,b)=>Number(a.match(/slide(\d+)/)[1])-Number(b.match(/slide(\d+)/)[1]));const extracted=[];
 for(const name of names){const slide=Number(name.match(/slide(\d+)/)[1]);const doc=new DOMParser().parseFromString(await zip.file(name).async('string'),'application/xml');const paragraphs=[...doc.getElementsByTagNameNS('*','p')].map(p=>[...p.getElementsByTagNameNS('*','t')].map(n=>n.textContent).join('')).map(t=>t.trim()).filter(t=>t.length>2&&!/^\d+$/.test(t));const topic=paragraphs[0]||`Slide ${slide}`;const body=paragraphs.slice(1).filter(t=>!/^https?:\/\//.test(t)&&!/^©/.test(t));if(!body.length)continue;
 const chunks=[];let chunk=[];for(const line of body){if(chunk.join(' ').length>500){chunks.push(chunk);chunk=[]}chunk.push(line)}if(chunk.length)chunks.push(chunk);
 chunks.forEach((lines,i)=>{const answer=lines.join('\n');const definition=lines.length===1&&lines[0].match(/^(.{3,65}?)\s*(?::|\s[-–—]\s)\s*(.{15,})$/);extracted.push({id:crypto.randomUUID(),slide,topic,question:definition?`What is ${definition[1]}?`:`${i?`Part ${i+1}: `:''}What does the lecture explain about ${topic.replace(/[?!.]+$/,'')}?`,answer:definition?definition[2]:answer,status:'new'})})}
 if(!extracted.length)throw Error('No readable slide text was found. Image-only slides need OCR or cards added manually.');next={title:file.name.replace(/\.pptx$/i,''),cards:extracted};message=`Created ${extracted.length} draft cards from slide text. Review questions in the library; diagrams and speaker notes are not included.`;
 }else throw Error('Choose a .pptx lecture or a .json deck.');deck=next;filter='all';view='study';save();resetQueue();
 }catch(e){message=e.message||'Could not read the file. Try another PowerPoint.'}finally{busy=false;render()}}
 document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)||editing)return;if(view!=='study'||!current())return;if(e.code==='Space'){e.preventDefault();flipped=!flipped;render()}else if(e.key==='1')rate('review');else if(e.key==='2')rate('known');else if(e.key==='ArrowRight'&&index<queue.length-1){index++;flipped=false;render()}else if(e.key==='ArrowLeft'&&index>0){index--;flipped=false;render()}});
resetQueue();render();
