export const MODULES=[
 {id:'pathobiology',name:'Pathobiology',code:'LS5009'},
 {id:'infection-immunity',name:'Infection and Immunity',code:'LS5008'},
 {id:'medical-genetics',name:'Medical Genetics',code:'LS5023'},
 {id:'physiology-research',name:'Medical Physiology, Research Methods and Skills',code:'LS5034'},
];
const bundled={'cell-injury':'pathobiology','cell-death':'pathobiology',microorganisms:'infection-immunity','genetic-variation':'medical-genetics',viruses:'infection-immunity'};
export function moduleFor(lecture){if(Object.hasOwn(lecture,'moduleId'))return MODULES.some(m=>m.id===lecture.moduleId)?lecture.moduleId:'';return bundled[lecture.lectureId]||''}
export function moduleOptions(selected,esc){return `<option value="" ${!selected?'selected':''}>Unassigned</option>`+MODULES.map(m=>`<option value="${m.id}" ${selected===m.id?'selected':''}>${esc(m.name)} (${m.code})</option>`).join('')}
export function moduleTotals(lectures,id){const group=lectures.filter(l=>moduleFor(l)===id);const total=group.reduce((s,l)=>s+l.count,0),studied=group.reduce((s,l)=>s+(l.studied||0),0);return {lectures:group.length,total,studied,percent:total?Math.round(studied/total*100):0}}
export function modulesWorkspace(lectures,esc){return `<section class="modules-workspace"><span class="eyebrow">YOUR MODULES</span><h2>Pick a module.</h2><p>Keep your lectures together and see your progress across each module.</p><div class="module-grid">${MODULES.map(m=>{const p=moduleTotals(lectures,m.id);return `<article class="module-entry"><button class="module-tile" data-module="${m.id}"><span class="module-code">${m.code}</span><h3>${esc(m.name)}</h3><p>${p.lectures} lecture${p.lectures===1?'':'s'} · ${p.total} cards</p><div class="module-progress-label"><span>${p.studied} cards studied</span><strong>${p.percent}%</strong></div><div class="progress"><i style="width:${p.percent}%"></i></div><span class="module-open">View lectures →</span></button><button type="button" class="button subtle module-summary-button" data-summary-module="${m.id}">Quick summary</button></article>`}).join('')}</div>${lectures.some(l=>!moduleFor(l))?`<button class="button subtle" data-module="unassigned">Unassigned lectures (${lectures.filter(l=>!moduleFor(l)).length}) →</button>`:''}</section>`}
