export function navigation({view,lectures,deck,user,syncLabel,esc,busy}){
 const extra=[['friends','Friends & streaks','friends-nav'],['settings','Appearance','settings-nav'],['account',user?'My account':'Sign in','account-nav'],['library','Card library',''],['slides','Slide reference','']];
 return `<aside class="simple-sidebar" ${busy?'inert':''}><a class="brand" href="#" aria-label="CHUDS.org"><img class="brand-logo" src="${import.meta.env.BASE_URL}chuds-logo.png" alt="" width="30" height="30"><span class="brand-name">CHUDS.org</span></a><nav class="primary-nav" aria-label="Main navigation"><button class="nav ${view==='study'?'active':''}" data-view="study" ${view==='study'?'aria-current="page"':''}><span>Study</span></button><button class="nav ${view==='lectures'?'active':''}" data-view="lectures" ${view==='lectures'?'aria-current="page"':''}><span>Lectures</span></button><button class="nav ${view==='modules'?'active':''}" data-view="modules" ${view==='modules'?'aria-current="page"':''}><span>Modules</span></button></nav><label class="lecture-switch"><span>Current lecture</span><select id="lecture-switch" aria-label="Switch lecture" ${busy?'disabled':''}>${lectures.length?lectures.map(l=>`<option value="${esc(l.lectureId)}" ${l.lectureId===deck?.lectureId?'selected':''}>${esc(l.lectureId==='microorganisms'?'Microorganisms':l.title)} · ${l.count} cards</option>`).join(''):'<option value="">Add your first lecture</option>'}</select></label><details class="workspace-menu ${extra.some(([v])=>v===view)?'current':''}"><summary>More <span aria-hidden="true">···</span></summary><nav class="workspace-menu-items" aria-label="More options">${extra.map(([v,label,cls])=>`<button class="nav ${cls} ${v===view?'active':''}" data-view="${v}" ${v===view?'aria-current="page"':''}><span>${label}</span></button>`).join('')}<div class="menu-divider"></div><button class="nav" id="curated"><span>${deck?.curated?'Reset this lecture':'Open Microorganisms'}</span></button></nav></details><div class="aside-bottom"><div class="privacy-dot"></div><div>${user?esc(user.email):'Made for your mind.'}<br><small>${user?esc(syncLabel):'Guest · saved in this browser'}</small></div></div></aside>`;
}
export function bindNavigation({openLecture}){
 document.getElementById('lecture-switch')?.addEventListener('change',e=>{if(e.target.value)openLecture(e.target.value)});
}
document.addEventListener('click',e=>{const menu=document.querySelector('.workspace-menu[open]');if(menu&&!menu.contains(e.target))menu.open=false});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const menu=document.querySelector('.workspace-menu[open]');if(menu){menu.open=false;menu.querySelector('summary').focus()}}});
