import {escapeHTML as esc} from './cloze.js';
import {MODULES,moduleFor} from './modules.js';
import {lectureSummary} from './summary-notes.js';
import './summaries.css';
export function quickSummaries({decks,waitSave,openLecture}){
 let dialog=null,generation=0,returnFocus=null;
 function close(){generation++;dialog?.close();dialog=null}
 async function open(kind,id){const token=++generation;try{await waitSave();const saved=await decks();if(token!==generation)return;const selected=kind==='module'?saved.filter(d=>moduleFor(d)===(id==='unassigned'?'':id)):saved.filter(d=>d.lectureId===id);const mod=MODULES.find(m=>m.id===id);const title=kind==='module'?(mod?`${mod.name} · ${mod.code}`:'Unassigned lectures'):(selected[0]?.title||'Lecture summary');const notes=selected.map(d=>({deck:d,summary:lectureSummary(d)}));
 if(!dialog)returnFocus=document.activeElement;const previous=returnFocus;const old=dialog;old?.close();old?.remove();dialog=document.createElement('dialog');const current=dialog;current.className='quick-summary';current.setAttribute('aria-labelledby','quick-summary-title');
 const sections=(summary,short=false)=>summary.sections.map(s=>`<section class="summary-section"><h3>${esc(s.title)}</h3><ul>${s.points.slice(0,short?2:undefined).map(p=>`<li>${esc(p)}</li>`).join('')}</ul></section>`).join('');
 current.innerHTML=`<header class="summary-header"><div><span>QUICK LEARNING · ${kind==='module'?'MODULE OVERVIEW':'LECTURE CHEAT SHEET'}</span><h2 id="quick-summary-title">${esc(title)}</h2></div><button type="button" class="button subtle" data-summary-close autofocus>Close</button></header><div class="summary-body">${kind==='module'?'<p class="summary-intro">Main ideas from the lectures you have added to this module. This overview grows as you add lectures.</p>':''}${notes.length?notes.map(({deck:d,summary:s})=>`<article class="summary-lecture">${kind==='module'?`<div class="summary-lecture-heading"><h2>${esc(d.title)}</h2><button type="button" class="button subtle" data-summary-lecture="${esc(d.lectureId)}">Full cheat sheet</button></div>`:''}<p class="summary-intro">${esc(s.intro)}</p>${!s.reviewed?'<p class="summary-source-note">Extracted from your saved cards; check any draft points against the lecture.</p>':''}${s.sections.length?sections(s,kind==='module'):'<p>Add some text-based cards to build a summary for this lecture.</p>'}<div class="summary-footer"><span>${d.cards.length} cards · ${d.slides?.length||0} source slides</span><button type="button" class="button primary" data-summary-study="${esc(d.lectureId)}">Start revision →</button></div></article>`).join(''):'<p class="summary-empty">No lectures have been added here yet. Add a lecture to create its quick-learning outline.</p>'}</div>`;
 current.querySelector('[data-summary-close]').onclick=()=>current.close();current.querySelectorAll('[data-summary-study]').forEach(b=>b.onclick=()=>{current.close();openLecture(b.dataset.summaryStudy)});current.querySelectorAll('[data-summary-lecture]').forEach(b=>b.onclick=()=>open('lecture',b.dataset.summaryLecture));current.addEventListener('close',()=>{current.remove();if(dialog===current){dialog=null;if(previous?.isConnected)previous.focus()}},{once:true});document.body.append(current);current.showModal();
 }catch{if(token!==generation)return;const error=document.createElement('dialog');error.className='quick-summary';error.innerHTML='<div class="summary-body"><p>Could not load this summary. Close and try again.</p><button class="button subtle">Close</button></div>';error.querySelector('button').onclick=()=>error.close();error.addEventListener('close',()=>error.remove(),{once:true});document.body.append(error);dialog=error;error.showModal()}}
 function bind(){document.querySelectorAll('[data-summary-lecture]').forEach(b=>b.onclick=()=>open('lecture',b.dataset.summaryLecture));document.querySelectorAll('[data-summary-module]').forEach(b=>b.onclick=()=>open('module',b.dataset.summaryModule))}
 return {bind,close};
}
