export const LECTURE_SUMMARIES={
 microorganisms:{intro:'Bacterial structure, growth, identification and community behaviour.',sections:[
 {title:'Bacterial cell plan',points:['Bacteria have a cytoplasmic membrane, cytoplasm, 70S ribosomes and a nucleoid; they do not have a membrane-bound nucleus.','The cytoplasmic membrane is a selective barrier and houses the electron transport chain.','Plasmids can carry virulence or antimicrobial-resistance genes; a prophage is bacteriophage genetic material maintained in a bacterium.']},
 {title:'Compare the envelopes',points:['Gram-positive bacteria typically have a thick peptidoglycan wall; Gram-negative bacteria have thin peptidoglycan plus an outer membrane.','The Gram-negative outer membrane provides an additional selective barrier.','Mycobacteria have a lipid-rich envelope containing mycolic acids. Wall-less bacteria lack a peptidoglycan wall.']},
 {title:'Match structures to functions',points:['Capsules and slime layers are extracellular coverings; extracellular polymeric substances help build the biofilm matrix.','Fimbriae mainly support attachment; conjugation pili support DNA transfer, and type IV pili can drive twitching motility.','Flagella support motility; endoflagella give spirochaetes a corkscrew motion.','Endospores are resistant survival structures made by a minority of bacteria, not a reproductive stage.']},
 {title:'Growth and colonies',points:['Growth follows lag → exponential → stationary → decline phases. Stationary phase reflects nutrient limitation and/or accumulated toxic products.','Describe colonies by form, margin, elevation, texture, opacity, consistency and pigment. Colony appearance alone does not establish species identity.','Biofilms are organised microbial communities in a matrix, often attached to a surface.']},
 {title:'Identification and classification',points:['Use multiple lines of evidence: morphology, biochemical behaviour, growth requirements and genomic information.','Distinguish oxygen requirements from temperature preferences; a microaerophile needs reduced oxygen.','Genus and species form the scientific name. Sequence type (ST) and clonal complex (CC) describe relatedness within typing schemes.']}
 ]},
 'genetic-variation':{intro:'How DNA changes arise, alter gene function and contribute to inherited disease.',sections:[
 {title:'The essential vocabulary',points:['A gene is a functional DNA sequence; an allele is a version of a gene, and its chromosomal position is its locus.','Genotype describes genetic constitution; phenotype is the observable result of genotype and other influences.','DNA is transcribed into RNA; mRNA is translated into protein. Read coding information in three-base codons.']},
 {title:'Where variation comes from',points:['Mutation is the ultimate source of new genetic sequence variation.','Somatic variants arise in body cells; germline variants can be passed to offspring.','Changes can involve single bases, insertions/deletions or expanded repeated sequences.']},
 {title:'Predict a coding change',points:['A synonymous substitution preserves the amino acid; missense changes it; nonsense introduces a premature stop codon.','An insertion/deletion not divisible by three shifts the reading frame in a coding sequence. Multiples of three can add/remove amino acids without shifting the frame.','A transition exchanges purine↔purine or pyrimidine↔pyrimidine; a transversion exchanges purine↔pyrimidine.']},
 {title:'Look beyond the coding sequence',points:['Regulatory variants can change transcription and gene expression.','Splice-site variants can alter RNA processing and therefore the final protein.','A variant’s effect depends on its location and consequence; not every sequence change is harmful.']},
 {title:'Connect function to disease',points:['Loss-of-function reduces or abolishes activity; gain-of-function increases activity or creates a new activity.','Dominance/recessiveness describes phenotype and inheritance, not simply whether a DNA change exists.','Huntington disease is a key repeat-expansion example: CAG expansion in HTT.']}
 ]},
 'cell-injury':{intro:'Why cells are injured, how they adapt, and when injury becomes irreversible.',sections:[
 {title:'Start with the cause',points:['Injury occurs when a stress exceeds the cell’s ability to maintain homeostasis or adapt.','Major causes include hypoxia/ischaemia, physical and chemical injury, infection, immune reactions, nutritional imbalance and genetic abnormalities.','Hypoxia is insufficient oxygen; ischaemia is reduced blood supply and also restricts nutrient delivery and waste removal.']},
 {title:'Reversible versus irreversible injury',points:['Functional and biochemical disturbances can occur before visible morphological changes.','Adaptation can maintain survival under stress; persistent or severe injury can progress to irreversible injury and cell death.','The outcome depends on the nature, severity and duration of the insult and the affected cell type.']},
 {title:'Compare the adaptations',points:['Hypertrophy increases cell size; hyperplasia increases cell number. They may occur together.','Atrophy reduces the size of previously developed cells/tissue; it is different from failure to develop normally.','Metaplasia replaces one differentiated cell type with another better suited to a stress.','Dysplasia means disordered growth/maturation. It is not synonymous with invasive cancer; invasion crosses the relevant tissue boundary.']},
 {title:'Why repair differs between tissues',points:['Labile cells regularly renew; stable cells can re-enter proliferation when stimulated; permanent cells have very limited regenerative capacity.','Damage to tissue rich in permanent cells, such as mature neurons, is difficult to repair through proliferation of surviving specialised cells.','Distinguish congenital (present at birth) from acquired (developing after birth) conditions.']},
 {title:'Papillomavirus extension',points:['Papillomaviruses infect cutaneous and mucosal epithelia.','CIN means cervical intraepithelial neoplasia; it describes abnormal intraepithelial changes, not automatically invasive cancer.','The lecture’s E5 model links viral effects to altered MHC class I surface transport and immune recognition.']}
 ]},
 'cell-death':{intro:'Recognise necrosis patterns and distinguish them from apoptosis.',sections:[
 {title:'The central comparison',points:['Necrosis usually involves cell swelling, loss of membrane integrity, leakage of contents and an inflammatory response.','Apoptosis involves cell shrinkage, chromatin condensation, fragmentation into apoptotic bodies and controlled clearance.','Apoptosis can be physiological or pathological; death mechanisms cannot be classified solely by whether they happen in disease.']},
 {title:'Recognise necrosis patterns',points:['Coagulative necrosis initially preserves tissue architecture and is typical of many ischaemic injuries outside the brain.','Liquefactive necrosis destroys architecture through digestion; important examples include brain infarction and abscesses.','Caseous necrosis has a cheese-like appearance and is classically associated with tuberculosis.','Fat necrosis can produce saponification: fatty acids combine with calcium to form soaps.']},
 {title:'Gangrene and nuclear changes',points:['Gangrene is a clinical description, rather than a separate microscopic pattern. Dry and wet gangrene differ in features and the contribution of infection/liquefaction.','Pyknosis = nuclear condensation; karyorrhexis = nuclear fragmentation; karyolysis = nuclear fading/dissolution.']},
 {title:'Apoptotic signalling and clearance',points:['Apoptosis can be triggered by signals from inside or outside the cell; the lecture links signalling to mitochondrial changes and chromatin fragmentation.','Apoptotic bodies are recognised and removed by phagocytes, limiting leakage and inflammation.','p53 can link serious DNA damage to cell-cycle arrest or apoptosis; failure of protective pathways can contribute to disease.']},
 {title:'A useful revision check',points:['For each example, identify the trigger, cell morphology, membrane integrity and inflammatory response before naming the process.','Do not assume all infection-related or neurodegenerative cell death uses only one pathway.']}
 ]},
 viruses:{intro:'Viral structure and genomes, infection cycles, persistence and prevention.',sections:[
 {title:'What a virus needs',points:['Viruses are acellular infectious agents that depend on living host cells for replication; a virion is a virus particle.','The genome is DNA or RNA, surrounded by a protein capsid. Some virions also have a lipid envelope.','Capsid symmetry and envelope status are different features. Mature HIV has a conical capsid core.']},
 {title:'Genomes and the Baltimore idea',points:['All viruses must produce mRNA that can be translated by the host. Baltimore classification groups viruses by how they reach that step.','Groups I–VII: dsDNA, ssDNA, dsRNA, +ssRNA, −ssRNA, RNA with reverse transcription, DNA with reverse transcription.','Positive-sense RNA can act as mRNA. Negative-sense and dsRNA viruses need RNA-dependent RNA polymerase to make mRNA.','Retroviruses use a DNA intermediate; having that intermediate does not change their virion genome from RNA to DNA.']},
 {title:'The infection cycle',points:['Attachment → entry/uncoating → genome/protein production → assembly → release.','Receptors help determine host/tissue range, but attachment alone does not guarantee productive infection.','Entry can involve fusion or endocytosis; bacteriophages can inject their genome.','Lysis destroys the cell; budding can release virions without immediately lysing it.']},
 {title:'Persistence and disease',points:['Lytic phage infection produces particles and releases them; lysogeny maintains phage DNA, with induction allowing a return to a lytic cycle.','Distinguish acute, chronic, latent and asymptomatic infection. Varicella-zoster latency usually uses episomal DNA in sensory neurons, not obligatory chromosome integration.','HPV can remain episomal; integration may contribute to cancer progression but is not required in every infection.','An animal-to-human spillover does not by itself prove sustained human-to-human transmission.']},
 {title:'Prevention, treatment and look-alikes',points:['Vaccines can use live attenuated, inactivated or subunit approaches. Live attenuated vaccines retain some replication ability.','HIV drug targets include entry, reverse transcriptase, integrase and protease; recognise which step each target affects.','Prions are infectious misfolded proteins without nucleic acid. Viroids are small naked circular RNA agents of plants and do not encode proteins.']}
 ]}
};
export function plainCard(card){const text=String(card.text||card.question||'').replace(/\{\{c\d+::([^{}]+)\}\}/g,(_,value)=>value.split('::')[0]).trim();return card.type==='cloze'?text:[text,String(card.answer||'').trim()].filter(Boolean).join(' — ')}
export function lectureSummary(deck){
 if(LECTURE_SUMMARIES[deck.lectureId])return {...LECTURE_SUMMARIES[deck.lectureId],reviewed:true};
 const groups=new Map();for(const card of deck.cards||[]){if(card.showImagesFront)continue;const point=plainCard(card);if(!point||point.length>650)continue;const topic=String(card.topic||'Key points');const points=groups.get(topic)||[];if(!points.includes(point)&&points.length<3)points.push(point);groups.set(topic,points)}
 return {intro:'A quick outline drawn from the cards in this lecture.',reviewed:false,sections:[...groups].slice(0,8).map(([title,points])=>({title,points}))};
}
const combinedInjury=LECTURE_SUMMARIES['cell-injury'];
LECTURE_SUMMARIES['cell-injury']={intro:'Cell basics, disease terminology and the main causes of cellular injury.',sections:[
 {title:'Cells and homeostasis',points:['A cell is the basic living structural and functional unit. Cells form tissues, which form organs and organ systems.','The cell membrane controls exchanges with the environment; organelles perform specialised functions.','Homeostasis is an actively maintained steady state, rather than the absence of change.']},
 {title:'Recognise disease',points:['Disease involves disturbance of normal function and may produce structural or functional abnormalities.','Symptoms are experienced by the patient; signs are observable findings.','An acquired condition develops after birth; congenital means present at birth and does not automatically mean inherited.']},
 combinedInjury.sections[0],
 {title:'Injury from the environment',points:['Physical injury includes extremes of temperature and other physical stresses. Chemical agents can disturb cellular pathways.','Infectious agents can directly damage tissue and/or provoke damaging host immune responses.','Immune reactions can themselves cause injury, including autoimmunity and hypersensitivity.']},
 {title:'Nutrition, genetics and congenital injury',points:['Both nutritional excess and deficiency can harm cells; examples include iron deficiency and vitamin D deficiency.','Genetic disorders may arise from DNA changes; familial disorders run in families.','A congenital abnormality may have a genetic or non-genetic cause.']}
]};
LECTURE_SUMMARIES['cell-injury-2']={intro:'How cells respond to injury: renewal capacity, adaptation and papillomavirus research.',sections:[
 combinedInjury.sections[3],combinedInjury.sections[1],combinedInjury.sections[2],
 {title:'Metaplasia, dysplasia and invasion',points:['Metaplasia changes the differentiated cell type, for example columnar to squamous epithelium in an irritated bronchus.','Dysplasia describes disordered cell growth and maturation; it is not automatically invasive cancer.','Distinguish intraepithelial changes from invasion into surrounding tissue.']},
 combinedInjury.sections[4]
]};
